format_version: 2
pipelines:
  pipeline-name:
    group: group-name
    materials:
      git-repo:
        git: https://github.com/gotham-learning/vue-gotham-todo.git
        branch: master
    stages:
      - first-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: cd
                    arguments:
                      - gotham-todo
                - exec:
                    command: bash
                    arguments:
                      - ./apply-infrastructure.sh
                - exec:
                    command: bash
                    arguments:
                      - ./build.sh
                - exec:
                    command: bash
                    arguments:
                      - ./copy-static-files.sh
